#!/bin/sh

# on Mac libtoolize is called glibtoolize
LIBTOOLIZE=libtoolize
if [ `uname -s` = Darwin ]; then
    LIBTOOLIZE=glibtoolize
fi
$LIBTOOLIZE -f -c --automake
aclocal
autoheader -f
autoconf
automake -a --foreign -f -c
